#Adi Pillai, arp3np@virginia.edu, 04/20/2021, "Makefile"
#Makefile for inlab9

CXX = clang $(CXX_FLAGS)
CXX_FLAGS = -Wall -g 
OBJECTS = linkedlist.c

hashTable: $(OBJECTS)
	$(CXX) $(OBJECTS)

hashTable.o: linkedlist.c

